### ISSUE TITLE
Needs a way to defined `background-position: center;`

### ISSUE THREAD

**Issue by nikgraf** [SentiaAnalytics/bs-css#165]
Currently I'm not sure how to do this. Actually there are many more ways how to define a background position: https://developer.mozilla.org/en-US/docs/Web/CSS/background-position

**Comment by lucasweng** [comment]
Hi @nikgraf 

I created a PR #167 so keyword values can be used to define background-position. Other ways can be used too, except for 3-value syntax (I think `backgroundPosition4` can serve the needs 😅 )

Though the implementation of `backgroundPosition` became a bit complicated in order to cover all possible types in the 2-value syntax. Would like to know @giraud's thoughts on the changes 🙂

**Comment by giraud** [comment]
thanks, can't look at it until next week

**Comment by nikgraf** [comment]
thanks @lucasweng 👏

**Comment by giraud** [comment]
thanks @lucasweng, it seems very good.

**Comment by nikgraf** [comment]
great, closing this issue now

**Comment by giraud** [comment]
fixed in 11.0.0
