### ISSUE TITLE
How to use glamor plugins?

### ISSUE THREAD

**Issue by rkoster** [SentiaAnalytics/bs-css#45]
Would like to use the [`increase-specificity.js`](https://github.com/threepointone/glamor/issues/235#issuecomment-294290122) plugin, to fix a conflict with material-ui-next. Would this be something we could inject [here](https://github.com/SentiaAnalytics/bs-css/blob/master/src/Css.re#L35-L36)?

**Comment by cullophid** [comment]
That is a good question. I dont want to tie the lib too much to Glamor.js since I will probably rewrite that bit in reason at a later time. 
Im hesitant of using something like increase-specificity plugin since it can already be quite difficult to understand how the css rules are applied.

I am looking into options for rendering to the styleprop instead of as a style element, but it is currently quite difficult due to ReasonReacts api

**Comment by mbrgm** [comment]
Following the rewrite, is there any way to emulate the behavior of `increase-specificity.js`?

**Comment by giraud** [comment]
Please, create a new issue if needed

**Comment by Coobaha** [comment]
@mbrgm you can use `&&` selector to increase class specificity
```reason
      selector("&&", [])
```
