### ISSUE TITLE
Expose `string_of` functions

### ISSUE THREAD

**Issue by alexeygolev** [SentiaAnalytics/bs-css#73]
It might be a good idea to expose the `string_of_length` and similar functions as sometimes they are needed. Normally when you're down to the `definition` level and you have constants defined elsewhere as `length`. At the moment they are hidden from the interface and I literally grabbed them from the source. But this way if bs-css changes my forked functions will get out of sync.
These functions are also useful when you have a theme and you need to add some inline styles. 
I would just alias the functions within a Utils submodule. I can make a pull request if you think it's a good idea

**Comment by alexeygolev** [comment]
@giraud We have a theme definition that uses bs-css types, but sometimes we need to use theme values in inline styles. If we were to define them as ints or floats we would lose the flexibility of the theme as the units would have to be defined in the styles that use the theme.

**Comment by giraud** [comment]
I suppose the problem is that you have to locally redefine the functions in your project when you want to use them in a style for example, like in the following screen:


![image](https://user-images.githubusercontent.com/239612/44708518-a20fb980-aaa7-11e8-93b2-f0d8ef27099c.png)


I have many small functions in my project for that.
I understand people don't want to redefine them, but I'm not sure that publishing the utilities functions in the Css API is a good thing.

Maybe, it would be interesting to add a function that can convert a list of rules to a js object and then use that js object as a react style (or anything else)


![image](https://user-images.githubusercontent.com/239612/44709305-99b87e00-aaa9-11e8-816c-fde765565746.png)


this way we keep the rules constraints, don't pollute the API with many utilities functions, and add the ability to use the rules outside the classname.

would that help ?

**Comment by giraud** [comment]
Master is exposing a Length type with a toString function, that should help with this issue
